apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allure-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: allure-ui
      labels:
        app: allure-ui
    spec:
      containers:
      - env:
        - name: ALLURE_DOCKER_PUBLIC_API_URL
          value: http://localhost:5050
        - name: ALLURE_DOCKER_PUBLIC_API_URL_PREFIX
        image: frankescobar/allure-docker-service-ui
        name: allure-ui
        ports:
        - containerPort: 5252
        resources: {}
      restartPolicy: Always
