apiVersion: v1
kind: Service
metadata:
  labels:
    app: allure-ui
  name: allure-ui
spec:
  type: NodePort
  ports:
  - name: "5252"
    port: 5252
    targetPort: 5252
  selector:
    app: allure-ui
status:
  loadBalancer: {}
