apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  - name: "50001"
    port: 50001
    targetPort: 50000
    nodePort: 30036
  selector:
    app: jenkins
